### PR TITLE
add update customers

### PR DESCRIPTION
**Pull request by liyingxin97**
update customers Information

### CODE REVIEW

**Comment by Bobby-Zien** [comment]
Hi Tina, could you also write the testing functions for your update api as I mentioned in the slack chat?

**Comment by liyingxin97** [comment]
> Hi Tina, could you also write the testing functions for your update api as I mentioned in the slack chat?

Hi Bobby, I just added the testing functions. Thank you for the reminder.

**Comment by ryanjcohen** [comment]
We have some failing tests on this branch, I can fix them but don't think we should merge yet

**Comment by ryanjcohen** [comment]
@liyingxin97 I did some quick test updates to this branch just because it was approved and wanted to make sure we didn't merge in any failing test cases to main. Just want to make sure these changes look ok to you

**Comment by ryanjcohen** [comment]
@devops-customers-squad/squad-members one thing I'm realizing is that we forgot to implement the subordinate addresses API (described in the issue). Anyone know what we're supposed to do in this case - should we make a new issue, or reopen the issue?

**Comment by Bobby-Zien** [comment]
> @devops-customers-squad/squad-members one thing I'm realizing is that we forgot to implement the subordinate addresses API (described in the issue). Anyone know what we're supposed to do in this case - should we make a new issue, or reopen the issue?

I think we can just move it under in progress again

**Pull request merged**
