### PR TITLE
Dome delete several addresses

### PR DESCRIPTION
**Pull request by domejiraphon**

### CODE REVIEW

**Comment by ryanjcohen** [comment]
I'm not able to run the behave tests with the change. Looks like all scenarios are followed by "Assertion Failed: Expected 404 to equal 200"

**Comment by domejiraphon** [comment]
Solved the 404 error.

**Comment by Bobby-Zien** [comment]
Hi dome, I'm thinking that maybe we can manually add addresses for the list customer's addresses BDD testing. Instead of adding a second addresses to the background. Sorry it was my misunderstanding of the code. My initail thought was that we need to have background for the addresses, but right now I think it's not necessary. Feel free work on the list customer's addresses issue, or I'd like to work on that :)

**Review by Bobby-Zien — CHANGES_REQUESTED** [review]
Please refer to my comment

**Comment by domejiraphon** [comment]
Okay, I can work on the new issue.

**Pull request closed without merging**
