### PR TITLE
Fix occasionally show up nosetests

### PR DESCRIPTION
**Pull request by domejiraphon**
I fixed the occasionally show up bug when running nosetests, and I tried to run the new code for 10 times. No code coverage reduce has shown up.

### CODE REVIEW

**Comment by domejiraphon** [comment]
The number of total line reduces by 3 lines so codecov goes down, but I already fixed the issue.

**Comment by ryanjcohen** [comment]
I'm wondering if we're failing codecov here because the total number of lines have changed. Wondering if we should increase coverage for the specific route function that's changed (if it happens to not have every line covered at the moment)

**Comment by domejiraphon** [comment]
What do you mean? Test cases now always cover all the lines.

**Comment by ryanjcohen** [comment]
Oh ok, I guess to deal with the -0.02% decrease then our options would be to add coverage somewhere else in routes.py or models.py, or to figure out how to get code cov to not block pull requests that only have a very small coverage decrease (could try to set that to a 0.02% threshold)

**Comment by ryanjcohen** [comment]
Ok, maybe then we should add a test for line 54 in models.py to avoid the pull request from being blocked by a -0.02% in coverage. was looking to see if there's a way to modify .coveragerc to specify a threshold for decreases in code coverage that should be permitted, but not finding anything on this at the moment

**Comment by domejiraphon** [comment]
I just added a test case for models.py.

**Review by ryanjcohen — APPROVED** [review]

**Pull request merged**
